Fix this error on Windows:
  File "C:\github\backgroundremover\backgroundremover\utilities.py", line 347, in download_files_from_github
    os.remove(part.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\temp\\test1\\tmph1fx9dbm'

Bypass temporary file, write to final model file directly.